### ISSUE TITLE
Design insight

### ISSUE THREAD

**Issue by deepanshnagaria** [niXman/binapi#47]
Hi, can you provide me with some insight into the design choices? 

- why are the classes defined in a way to abstract out impl subclass? (What do WebSockets class and corresponding impl signify? and why they cannot be the same or have been separated)?
- Why was there a need for weak pointer maintenance for connection maintenance in the map?

**Comment by niXman** [comment]
> why are the classes defined in a way to abstract out impl subclass?

this is usually done in three cases:
1) when need to hide implementation details. just in an aesthetic case.
2) when need to hide implementation details so that when you make changes to the implementation, only the C++ file in which the implementation is located is recompiled.
3) when need to compile the code in the form of a dll/so library, and when changing the types or the number of data-members, it was possible to replace only one specific dll/so because the ABI (Application binary Interface) always remains unchanged.

> Why was there a need for weak pointer maintenance for connection maintenance in the map?
because this method allows to automatically manage the lifetime of objects. there is no need to manually delete them.

**Comment by deepanshnagaria** [comment]
hi, thanks for the response, wanted to ask one more thing, about the use of multi buffer specifically. What made you choose it over others even though there is an extra copt involved (strbuf)?

**Comment by niXman** [comment]
because this allows not to relocate the internal storage and avoid copying, but simply add the received data to the list of buffers.

**Comment by niXman** [comment]
please close.
